service: xugera-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  stage: ${opt:stage, 'test'}  # Set default stage to 'dev'
  environment:
    MONGO_URI: ${env:MONGO_URI}  # MongoDB connection URI from environment

custom:
  dotenv:
    path: .env.${self:provider.stage}

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - src/tests/**
