import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'transactions',
      columns: [
        { name: 'transaction_date', type: 'number', isIndexed: true },
        { name: 'from_account', type: 'string', isIndexed: true },
        { name: 'to_account', type: 'string', isOptional: true, isIndexed: true },
        { name: 'category', type: 'string', isOptional: true, isIndexed: true },
        { name: 'amount', type: 'number' }
      ]
    }),
    tableSchema({
      name: 'categories',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'icon', type: 'string', isOptional: true },
        { name: 'parent', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' }
      ]
    }),
    tableSchema({
      name: 'accounts',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' }
      ]
    })
  ]
});

// Auto-generated from Mongoose models on 2025-06-11T08:24:57.382Z
// Do not edit this file manually - regenerate using: npm run generate:schema